name: PyDocs

on:
  push:
    branches:
      - master
      - pydocs
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Generate docs
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipx
          pipx install 'pydoc-markdown>=4.0.0,<5.0.0'

      - name: Generate markdown docs
        run: |
          pydoc-markdown -vv

      - name: Upload markdown artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-dir
          path: docs/

  pull:
    name: Open pull request
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout docs repository
        uses: actions/checkout@v2
        with:
          repository: 'PaloAltoNetworks/cortex.pan.dev'

      - name: Download markdown artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs-dir
          path: docs/

      - name: Commit changes
        run: |
          git config --global user.email "sserrata@paloaltonetworks.com"
          git config --global user.name "Steven Serrata"
          git checkout -b pydocs
          git add .
          git commit -m "update pydocs"
          git status

      - name: Create Pull Request
        id: pydocs
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update pydocs
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          delete-branch: true
          title: '[PyDocs] Update python docs'
          body: |
            Update pydocs
            - Updated with `pydoc-markdown`

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.pydocs.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pydocs.outputs.pull-request-url }}"